---
title: "First Knit"
author: "Cadence Gorden"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer
I attended high school at Rancho Cucamonga high. During 2020, I transferred to California Virtual Academies and graduated from there in June. I am better at math than english. I have always been better at numbers than words. In school I have always gotten a better grade in math and have done my best in math. In english I always pass but I never do as well as I have done in math.      
  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
 At home I have two computers, a Apple and a Chrome. I use my chrome the most often. I believe I am a 6 at computers. The internet access at my home is pretty good.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
 I prefer my normal first name, Cadence.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   
   My end goal of college is to become a medical examiner. My greatest interest/subject is music studies. I would like to get my bachelors in biology and my MD. 
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have never been to a foreign country but one day I would like to go to Japan. I have not been in the military but if I was I would be in the air force. 
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I am taking math 116. I did not know that math 116 counts as taking statistics in several transfer institutions. I just need to pass this class and my plan is to become a medical examiner.  
   
 






  




